site_name: Today I Learned
plugins:
  - search
  - social
  - privacy
  - tags
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
  - git-authors
  - blog:
      post_url_format: "{slug}"
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - header.autohide
    - announce.dismiss
  font:
    text: Roboto
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - footnotes
  - md_in_html

nav:
  - Blog:
    - blog/index.md
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/techbrunchfr
    - icon: fontawesome/brands/github 
      link: https://github.com/Techbrunch

#repo_url: https://github.com/Techbrunch/techbrunch-website
site_url: https://www.techbrunch.fr # required for social cards
